# Generated by Django 4.2.3 on 2023-08-02 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeeexperience_employeeeducation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeexperience',
            old_name='comany2salary',
            new_name='company2salary',
        ),
    ]
